### PR TITLE
Fix bug when response is null in ContentHashETagAttribute #178

### PR DESCRIPTION
**Pull request by TMiNus**

### CODE REVIEW

**Comment by johnib** [comment]
Was this merged already?

**Comment by aliostad** [comment]
No it uses C# 5 features. Do you have an issue with it?

**Comment by johnib** [comment]
I'm not using this library. I would like to - so I've checked about open issues before I get into this.

**Comment by aliostad** [comment]
Well it has been out there 5 years - many including myself use it everyday in production. Support for .NET core is also coming.

**Comment by aliostad** [comment]
New versions released

**Pull request closed without merging**
