### PR TITLE
Add support for RESTful attribute based routing with pattern matching…

### PR DESCRIPTION
**Pull request by zacharoth**
… for cache invalidation and attribute based cache control policy support

FYI @FLGMwt @ryanhallcs @eouw0o83hf

### CODE REVIEW

**Comment by aliostad** [comment]
Sorry moved house, do not have internet at the mo... will get back to you next week.

**Comment by aliostad** [comment]
Same applies here.

First of all, there is nothing RESTful about attribute based routing. REST is an architectural pattern and attribute based routing is a minor technique in ASP.NET

Also the extension points have been provided within the CacheCow project, but it does not mean each and every such extensions must then be homed with the mother project. 

I am sorry that this PR gets refused but it feels like this could be an extension which can have its own home with you being the author and owner 😄

**Comment by zacharoth** [comment]
Apologies if the PR title was vague. I didn't mean to suggest that attribute-based routing magically made your service RESTful. The PR was to allow a RESTful service that happens to use attribute-based routing to be compatible with CacheCow. 

Same thing as my comment on my other PR -- just sharing back some updates we made to fit our use case.

**Comment by ahmedalejo** [comment]
@aliostad i really don´t get your opinion about Attribute based routing, i do not use ASP.NET per sei and use attribute based routing for my self-hosted WebAPI, it makes life better.

Could you shed some light on `Àttribute based routing`

It´s way much better to include this support here and later move it to another repo if need be.
The PR is already there, no need to setup nuget and all the rest, but it´s your repo you have the right to curate it as you see fit.

**Pull request closed without merging**
